"""
Eventi curati a mano — verificati e versionati nel codice.

Servono a garantire i contenuti iconici (MotoGP, calcio, ecc.) che la lista
"Accadde oggi" di Wikipedia NON copre in modo affidabile. Ogni evento appare nel
feed del suo giorno (month, day), con l'anno reale e gli anni-fa ricalcolati.

REGOLA D'ORO: qui dentro solo fatti e date VERIFICATI da fonte (campo `source`).
Mai inventare date o numeri.

Made in Italy 🇮🇹
"""

from typing import List

LANGS = ("it", "en", "es")

# Immagini recuperate automaticamente da Wikipedia (vedi scratchpad/fetch_curated_images.py).
# Opzionali: se il file manca o un evento non ha immagine, si usa il fallback per categoria.
try:
    from curated_images import IMAGE_URLS
except Exception:
    IMAGE_URLS = {}

# Ogni voce:
# {
#   "id": "slug-univoco",              # id stabile in kebab-case
#   "day": 22, "month": 6, "year": 1986,
#   "kind": "event",                   # 'event' | 'birth' | 'death'
#   "category": "sports",
#   "subcategory": "football",         # deve combaciare con interests.ts
#   "scope": "global",
#   "countries": ["AR", "GB"],
#   "origin": "AR",
#   "title": {"it": "...", "en": "...", "es": "..."},
#   "text":  {"it": "...", "en": "...", "es": "..."},
#   "image_url": "https://upload.wikimedia.org/...",  # opzionale (None -> fallback categoria)
#   "wiki_url": {"it": "...", "en": "...", "es": "..."},  # o una singola stringa
#   "source": "come/da dove e' stata verificata la data",
# }
CURATED_EVENTS: List[dict] = [
    # ---------------- MotoGP / motociclismo ----------------
    {
        "id": "marquez-primo-titolo-motogp-2013", "day": 10, "month": 11, "year": 2013,
        "kind": "event", "category": "sports", "subcategory": "motogp", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Márquez, campione MotoGP da rookie",
                   "en": "Márquez, MotoGP champion as a rookie",
                   "es": "Márquez, campeón de MotoGP de novato"},
        "text": {"it": "A Valencia Marc Márquez chiude terzo e vince il titolo MotoGP al primo anno, diventando il più giovane campione della classe regina.",
                  "en": "At Valencia, Marc Márquez finished third and won the MotoGP title in his rookie year, becoming the youngest premier-class champion.",
                  "es": "En Valencia, Marc Márquez fue tercero y ganó el título de MotoGP en su año de novato, siendo el campeón más joven de la categoría reina."},
        "wiki_url": "https://en.wikipedia.org/wiki/2013_Valencian_Community_motorcycle_Grand_Prix",
        "source": "Wikipedia '2013 Valencian Community motorcycle Grand Prix' — 10/11/2013.",
    },
    {
        "id": "rossi-prima-vittoria-yamaha-2004", "day": 18, "month": 4, "year": 2004,
        "kind": "event", "category": "sports", "subcategory": "motogp", "scope": "global",
        "countries": ["IT", "ZA"], "origin": "IT",
        "title": {"it": "Rossi vince alla prima con la Yamaha",
                   "en": "Rossi wins first race with Yamaha",
                   "es": "Rossi gana en su debut con Yamaha"},
        "text": {"it": "A Welkom (Sudafrica) Valentino Rossi vince alla prima gara con la Yamaha, dopo la partenza dalla pole, battendo Max Biaggi.",
                  "en": "At Welkom (South Africa) Valentino Rossi won his very first race on a Yamaha, from pole, beating Max Biaggi.",
                  "es": "En Welkom (Sudáfrica) Valentino Rossi ganó su primera carrera con Yamaha, saliendo desde la pole, superando a Max Biaggi."},
        "wiki_url": "https://en.wikipedia.org/wiki/2004_South_African_motorcycle_Grand_Prix",
        "source": "Wikipedia '2004 South African motorcycle Grand Prix' (Welkom) — 18/4/2004.",
    },
    {
        "id": "rossi-primo-titolo-500cc-2001", "day": 14, "month": 10, "year": 2001,
        "kind": "event", "category": "sports", "subcategory": "motogp", "scope": "global",
        "countries": ["IT", "AU"], "origin": "IT",
        "title": {"it": "Rossi, primo titolo nella classe 500",
                   "en": "Rossi's first 500cc world title",
                   "es": "Rossi, primer título en 500cc"},
        "text": {"it": "A Phillip Island Valentino Rossi vince la gara e conquista il primo titolo mondiale nella classe 500, l'ultima dell'era 500cc.",
                  "en": "At Phillip Island, Valentino Rossi won the race and clinched his first 500cc world title, the last of the 500cc era.",
                  "es": "En Phillip Island, Valentino Rossi ganó la carrera y conquistó su primer título mundial de 500cc, el último de la era 500cc."},
        "wiki_url": "https://en.wikipedia.org/wiki/2001_Australian_motorcycle_Grand_Prix",
        "source": "Wikipedia '2001 Australian motorcycle Grand Prix' (Phillip Island) — 14/10/2001.",
    },
    {
        "id": "rossi-stoner-laguna-seca-2008", "day": 20, "month": 7, "year": 2008,
        "kind": "event", "category": "sports", "subcategory": "motogp", "scope": "global",
        "countries": ["IT", "AU", "US"], "origin": "IT",
        "title": {"it": "Rossi-Stoner, duello a Laguna Seca",
                   "en": "Rossi vs Stoner duel at Laguna Seca",
                   "es": "Duelo Rossi-Stoner en Laguna Seca"},
        "text": {"it": "A Laguna Seca Valentino Rossi batte Casey Stoner dopo un duello celebre, con il sorpasso al Cavatappi. Rossi vince il GP degli Stati Uniti.",
                  "en": "At Laguna Seca Valentino Rossi beat Casey Stoner after a famous duel, including the pass at the Corkscrew. Rossi won the United States GP.",
                  "es": "En Laguna Seca Valentino Rossi venció a Casey Stoner tras un célebre duelo, con el adelantamiento en el Sacacorchos. Rossi ganó el GP de EE.UU."},
        "wiki_url": "https://en.wikipedia.org/wiki/2008_United_States_motorcycle_Grand_Prix",
        "source": "Wikipedia '2008 United States motorcycle Grand Prix' — 20/7/2008.",
    },
    {
        "id": "agostini-ultima-vittoria-1976", "day": 29, "month": 8, "year": 1976,
        "kind": "event", "category": "sports", "subcategory": "motogp", "scope": "global",
        "countries": ["IT", "DE"], "origin": "IT",
        "title": {"it": "L'ultima vittoria di Agostini",
                   "en": "Agostini's last Grand Prix win",
                   "es": "La última victoria de Agostini"},
        "text": {"it": "Al Nürburgring Giacomo Agostini vince sotto la pioggia il GP di Germania 500: è la sua ultima vittoria iridata e l'ultima di un 4 tempi in 500.",
                  "en": "At the Nürburgring Giacomo Agostini won the 500cc German GP in the rain: his last Grand Prix win and the last for a four-stroke in the 500cc class.",
                  "es": "En Nürburgring Giacomo Agostini ganó bajo la lluvia el GP de Alemania de 500: su última victoria y la última de un cuatro tiempos en 500cc."},
        "wiki_url": "https://en.wikipedia.org/wiki/1976_German_motorcycle_Grand_Prix",
        "source": "Wikipedia '1976 German motorcycle Grand Prix' — 29/8/1976.",
    },
    # ---------------- Calcio ----------------
    {
        "id": "maradona-mano-de-dios-1986", "day": 22, "month": 6, "year": 1986,
        "kind": "event", "category": "sports", "subcategory": "football", "scope": "global",
        "countries": ["AR", "GB"], "origin": "AR",
        "title": {"it": "La Mano de Dios di Maradona",
                   "en": "Maradona's Hand of God",
                   "es": "La Mano de Dios de Maradona"},
        "text": {"it": "Nei quarti del Mondiale 1986 all'Azteca, Maradona segna all'Inghilterra la 'Mano de Dios' e il 'Gol del secolo'. Argentina-Inghilterra 2-1.",
                  "en": "In the 1986 World Cup quarter-final at the Azteca, Maradona scored the 'Hand of God' and the 'Goal of the Century' against England. Argentina won 2-1.",
                  "es": "En los cuartos del Mundial 1986 en el Azteca, Maradona marcó la 'Mano de Dios' y el 'Gol del siglo' ante Inglaterra. Argentina ganó 2-1."},
        "wiki_url": "https://en.wikipedia.org/wiki/Argentina_v_England_(1986_FIFA_World_Cup)",
        "source": "Wikipedia 'Argentina v England (1986 FIFA World Cup)' — 22/6/1986.",
    },
    {
        "id": "iniesta-gol-finale-mondiale-2010", "day": 11, "month": 7, "year": 2010,
        "kind": "event", "category": "sports", "subcategory": "football", "scope": "global",
        "countries": ["ES", "NL"], "origin": "ES",
        "title": {"it": "Il gol di Iniesta, la Spagna campione del mondo",
                   "en": "Iniesta's goal wins Spain the World Cup",
                   "es": "El gol de Iniesta da el Mundial a España"},
        "text": {"it": "Nella finale di Johannesburg Andrés Iniesta segna al 116' e la Spagna batte l'Olanda 1-0, vincendo il suo primo Mondiale.",
                  "en": "In the Johannesburg final Andrés Iniesta scored in the 116th minute as Spain beat the Netherlands 1-0 to win its first World Cup.",
                  "es": "En la final de Johannesburgo Andrés Iniesta marcó en el minuto 116 y España venció 1-0 a Países Bajos, ganando su primer Mundial."},
        "wiki_url": "https://en.wikipedia.org/wiki/2010_FIFA_World_Cup_Final",
        "source": "Wikipedia '2010 FIFA World Cup Final' — 11/7/2010.",
    },
    {
        "id": "maracanazo-1950", "day": 16, "month": 7, "year": 1950,
        "kind": "event", "category": "sports", "subcategory": "football", "scope": "global",
        "countries": ["UY", "BR"], "origin": "UY",
        "title": {"it": "Il Maracanazo: l'Uruguay batte il Brasile",
                   "en": "The Maracanazo: Uruguay beats Brazil",
                   "es": "El Maracanazo: Uruguay vence a Brasil"},
        "text": {"it": "Nella gara decisiva del Mondiale 1950 al Maracanã l'Uruguay batte il Brasile 2-1 e vince il titolo, davanti a quasi 200.000 spettatori.",
                  "en": "In the decisive match of the 1950 World Cup at the Maracanã, Uruguay beat Brazil 2-1 to win the title before a huge crowd.",
                  "es": "En el partido decisivo del Mundial 1950 en el Maracaná, Uruguay venció 2-1 a Brasil y ganó el título ante una multitud enorme."},
        "wiki_url": "https://en.wikipedia.org/wiki/Maracanazo",
        "source": "Wikipedia 'Maracanazo' — 16/7/1950.",
    },
    {
        "id": "inghilterra-campione-mondiale-1966", "day": 30, "month": 7, "year": 1966,
        "kind": "event", "category": "sports", "subcategory": "football", "scope": "global",
        "countries": ["GB", "DE"], "origin": "GB",
        "title": {"it": "L'Inghilterra campione del mondo 1966",
                   "en": "England win the 1966 World Cup",
                   "es": "Inglaterra campeona del mundo 1966"},
        "text": {"it": "A Wembley l'Inghilterra batte la Germania Ovest 4-2 dopo i supplementari e vince il Mondiale: Geoff Hurst segna una tripletta.",
                  "en": "At Wembley England beat West Germany 4-2 after extra time to win the World Cup, with Geoff Hurst scoring a hat-trick.",
                  "es": "En Wembley Inglaterra venció 4-2 a Alemania Occidental en la prórroga y ganó el Mundial, con un triplete de Geoff Hurst."},
        "wiki_url": "https://en.wikipedia.org/wiki/1966_FIFA_World_Cup_Final",
        "source": "Wikipedia '1966 FIFA World Cup Final' — 30/7/1966.",
    },
    {
        "id": "baggio-rigore-finale-mondiale-1994", "day": 17, "month": 7, "year": 1994,
        "kind": "event", "category": "sports", "subcategory": "football", "scope": "global",
        "countries": ["BR", "IT"], "origin": "IT",
        "title": {"it": "Il rigore di Baggio nella finale del 1994",
                   "en": "Baggio's penalty in the 1994 final",
                   "es": "El penalti de Baggio en la final de 1994"},
        "text": {"it": "Al Rose Bowl la finale Brasile-Italia finisce 0-0 e va ai rigori: Roberto Baggio calcia alto l'ultimo tiro e il Brasile vince il Mondiale.",
                  "en": "At the Rose Bowl the Brazil-Italy final ended 0-0 and went to penalties: Roberto Baggio shot over the bar and Brazil won the World Cup.",
                  "es": "En el Rose Bowl la final Brasil-Italia acabó 0-0 y fue a penaltis: Roberto Baggio la tiró por encima y Brasil ganó el Mundial."},
        "wiki_url": "https://en.wikipedia.org/wiki/1994_FIFA_World_Cup_Final",
        "source": "Wikipedia '1994 FIFA World Cup Final' — 17/7/1994.",
    },
    # ---------------- Altre leggende ----------------
    {
        "id": "bolt-100m-record-pechino-2008", "day": 16, "month": 8, "year": 2008,
        "kind": "event", "category": "sports", "subcategory": "olympics", "scope": "global",
        "countries": ["JM", "CN"], "origin": "JM",
        "title": {"it": "Bolt, record del mondo nei 100m a Pechino",
                   "en": "Bolt's 100m world record in Beijing",
                   "es": "Bolt, récord mundial de 100m en Pekín"},
        "text": {"it": "Alle Olimpiadi di Pechino Usain Bolt vince i 100 metri in 9.69, record del mondo, rallentando già prima del traguardo.",
                  "en": "At the Beijing Olympics Usain Bolt won the 100 metres in 9.69, a world record, even easing up before the finish.",
                  "es": "En los Juegos de Pekín Usain Bolt ganó los 100 metros en 9.69, récord mundial, aflojando antes de la meta."},
        "wiki_url": "https://en.wikipedia.org/wiki/Usain_Bolt",
        "source": "Wikipedia 'Usain Bolt' (finale 100m Pechino) — 16/8/2008.",
    },
    {
        "id": "beamon-salto-lungo-record-1968", "day": 18, "month": 10, "year": 1968,
        "kind": "event", "category": "sports", "subcategory": "olympics", "scope": "global",
        "countries": ["US", "MX"], "origin": "US",
        "title": {"it": "Il salto di Bob Beamon a Città del Messico",
                   "en": "Bob Beamon's leap in Mexico City",
                   "es": "El salto de Bob Beamon en Ciudad de México"},
        "text": {"it": "Alle Olimpiadi di Città del Messico Bob Beamon salta 8,90 m nel lungo, record del mondo che dura quasi 23 anni.",
                  "en": "At the Mexico City Olympics Bob Beamon jumped 8.90 m in the long jump, a world record that stood for almost 23 years.",
                  "es": "En los Juegos de Ciudad de México Bob Beamon saltó 8,90 m en longitud, récord mundial que duró casi 23 años."},
        "wiki_url": "https://en.wikipedia.org/wiki/Bob_Beamon",
        "source": "Wikipedia 'Bob Beamon' — 18/10/1968.",
    },
    {
        "id": "rumble-in-the-jungle-1974", "day": 30, "month": 10, "year": 1974,
        "kind": "event", "category": "sports", "subcategory": "boxing", "scope": "global",
        "countries": ["US", "CD"], "origin": "US",
        "title": {"it": "Rumble in the Jungle: Ali batte Foreman",
                   "en": "Rumble in the Jungle: Ali beats Foreman",
                   "es": "Rumble in the Jungle: Ali vence a Foreman"},
        "text": {"it": "A Kinshasa (Zaire) Muhammad Ali batte per KO all'ottava ripresa George Foreman e riconquista il titolo mondiale dei pesi massimi.",
                  "en": "In Kinshasa (Zaire) Muhammad Ali knocked out George Foreman in the eighth round to regain the world heavyweight title.",
                  "es": "En Kinsasa (Zaire) Muhammad Ali venció por KO en el octavo asalto a George Foreman y recuperó el título mundial de los pesos pesados."},
        "wiki_url": "https://en.wikipedia.org/wiki/The_Rumble_in_the_Jungle",
        "source": "Wikipedia 'The Rumble in the Jungle' — 30/10/1974.",
    },
    # ===================== STORIA / POLITICA =====================
    {
        "id": "caduta-muro-berlino-1989", "day": 9, "month": 11, "year": 1989,
        "kind": "event", "category": "wars", "subcategory": "cold_war", "scope": "global",
        "countries": ["DE"], "origin": "DE",
        "title": {"it": "Cade il Muro di Berlino", "en": "The Berlin Wall falls", "es": "Cae el Muro de Berlín"},
        "text": {"it": "La Germania Est apre i valichi e la folla abbatte il Muro di Berlino, simbolo della fine della Guerra Fredda.",
                  "en": "East Germany opens the crossings and crowds tear down the Berlin Wall, a symbol of the Cold War's end.",
                  "es": "Alemania Oriental abre los pasos y la multitud derriba el Muro de Berlín, símbolo del fin de la Guerra Fría."},
        "wiki_url": "https://it.wikipedia.org/wiki/Caduta_del_muro_di_Berlino",
        "source": "Wikipedia 'Fall of the Berlin Wall' — 9/11/1989.",
    },
    {
        "id": "sbarco-normandia-d-day-1944", "day": 6, "month": 6, "year": 1944,
        "kind": "event", "category": "wars", "subcategory": "world_wars", "scope": "global",
        "countries": ["FR", "US", "GB", "CA"], "origin": "US",
        "title": {"it": "Sbarco in Normandia (D-Day)", "en": "D-Day: the Normandy landings", "es": "Desembarco de Normandía (Día D)"},
        "text": {"it": "Gli Alleati sbarcano sulle spiagge della Normandia: la più grande invasione anfibia della storia apre il fronte occidentale.",
                  "en": "Allied forces land on the beaches of Normandy, the largest amphibious invasion in history, opening the Western Front.",
                  "es": "Las fuerzas aliadas desembarcan en las playas de Normandía, la mayor invasión anfibia de la historia, y abren el frente occidental."},
        "wiki_url": "https://it.wikipedia.org/wiki/Sbarco_in_Normandia",
        "source": "Wikipedia 'Normandy landings' — 6/6/1944.",
    },
    {
        "id": "i-have-a-dream-mlk-1963", "day": 28, "month": 8, "year": 1963,
        "kind": "event", "category": "politics", "subcategory": "human_rights", "scope": "global",
        "countries": ["US"], "origin": "US",
        "title": {"it": "«I Have a Dream» di Martin Luther King", "en": "Martin Luther King's 'I Have a Dream' speech", "es": "«I Have a Dream» de Martin Luther King"},
        "text": {"it": "Davanti al Lincoln Memorial, Martin Luther King pronuncia «I Have a Dream» durante la Marcia su Washington per i diritti civili.",
                  "en": "At the Lincoln Memorial, Martin Luther King delivers his 'I Have a Dream' speech during the March on Washington for civil rights.",
                  "es": "Ante el Lincoln Memorial, Martin Luther King pronuncia «I Have a Dream» durante la Marcha sobre Washington por los derechos civiles."},
        "wiki_url": "https://it.wikipedia.org/wiki/I_have_a_dream",
        "source": "Wikipedia 'I Have a Dream' — 28/8/1963.",
    },
    {
        "id": "assassinio-jfk-1963", "day": 22, "month": 11, "year": 1963,
        "kind": "event", "category": "politics", "subcategory": "assassinations", "scope": "global",
        "countries": ["US"], "origin": "US",
        "title": {"it": "Assassinio di John F. Kennedy", "en": "Assassination of John F. Kennedy", "es": "Asesinato de John F. Kennedy"},
        "text": {"it": "Il presidente degli Stati Uniti John F. Kennedy viene ucciso a colpi d'arma da fuoco durante un corteo a Dallas, in Texas.",
                  "en": "U.S. President John F. Kennedy is shot and killed while riding in a motorcade in Dallas, Texas.",
                  "es": "El presidente de EE. UU. John F. Kennedy es asesinado a tiros durante una caravana en Dallas, Texas."},
        "wiki_url": "https://it.wikipedia.org/wiki/Assassinio_di_John_Fitzgerald_Kennedy",
        "source": "Wikipedia 'Assassination of John F. Kennedy' — 22/11/1963.",
    },
    {
        "id": "presa-della-bastiglia-1789", "day": 14, "month": 7, "year": 1789,
        "kind": "event", "category": "wars", "subcategory": "revolutions", "scope": "global",
        "countries": ["FR"], "origin": "FR",
        "title": {"it": "Presa della Bastiglia", "en": "Storming of the Bastille", "es": "Toma de la Bastilla"},
        "text": {"it": "Il popolo di Parigi assalta la fortezza della Bastiglia: è la scintilla della Rivoluzione francese.",
                  "en": "The people of Paris storm the Bastille fortress, the spark that ignites the French Revolution.",
                  "es": "El pueblo de París asalta la fortaleza de la Bastilla, la chispa que enciende la Revolución francesa."},
        "wiki_url": "https://it.wikipedia.org/wiki/Presa_della_Bastiglia",
        "source": "Wikipedia 'Storming of the Bastille' — 14/7/1789.",
    },
    {
        "id": "assassinio-gandhi-1948", "day": 30, "month": 1, "year": 1948,
        "kind": "event", "category": "politics", "subcategory": "assassinations", "scope": "global",
        "countries": ["IN"], "origin": "IN",
        "title": {"it": "Assassinio del Mahatma Gandhi", "en": "Assassination of Mahatma Gandhi", "es": "Asesinato de Mahatma Gandhi"},
        "text": {"it": "Il leader pacifista indiano Mahatma Gandhi viene ucciso a Nuova Delhi mentre si reca a una preghiera pubblica.",
                  "en": "Indian independence leader Mahatma Gandhi is shot dead in New Delhi as he walks to a public prayer meeting.",
                  "es": "El líder pacifista indio Mahatma Gandhi es asesinado en Nueva Delhi mientras se dirige a una oración pública."},
        "wiki_url": "https://it.wikipedia.org/wiki/Assassinio_di_Gandhi",
        "source": "Wikipedia 'Assassination of Mahatma Gandhi' — 30/1/1948.",
    },
    {
        "id": "liberazione-nelson-mandela-1990", "day": 11, "month": 2, "year": 1990,
        "kind": "event", "category": "politics", "subcategory": "human_rights", "scope": "global",
        "countries": ["ZA"], "origin": "ZA",
        "title": {"it": "Nelson Mandela liberato dal carcere", "en": "Nelson Mandela released from prison", "es": "Nelson Mandela liberado de prisión"},
        "text": {"it": "Dopo 27 anni di prigionia, Nelson Mandela torna libero: passo decisivo verso la fine dell'apartheid in Sudafrica.",
                  "en": "After 27 years in prison, Nelson Mandela walks free, a decisive step toward the end of apartheid in South Africa.",
                  "es": "Tras 27 años en prisión, Nelson Mandela queda libre, un paso decisivo hacia el fin del apartheid en Sudáfrica."},
        "wiki_url": "https://it.wikipedia.org/wiki/Nelson_Mandela",
        "source": "Wikipedia / South African History Online — 11/2/1990.",
    },
    {
        "id": "referendum-repubblica-italiana-1946", "day": 2, "month": 6, "year": 1946,
        "kind": "event", "category": "politics", "subcategory": "elections", "scope": "global",
        "countries": ["IT"], "origin": "IT",
        "title": {"it": "Nasce la Repubblica Italiana", "en": "Italy becomes a Republic", "es": "Nace la República Italiana"},
        "text": {"it": "Con il referendum a suffragio universale gli italiani scelgono la repubblica al posto della monarchia. È la Festa della Repubblica.",
                  "en": "In a universal-suffrage referendum, Italians choose a republic over the monarchy, commemorated as Republic Day.",
                  "es": "En un referéndum por sufragio universal, los italianos eligen la república frente a la monarquía; es la Fiesta de la República."},
        "wiki_url": "https://it.wikipedia.org/wiki/Referendum_istituzionale_del_1946_in_Italia",
        "source": "Wikipedia 'Referendum istituzionale 1946' — 2/6/1946.",
    },
    # ===================== CULTURA =====================
    {
        "id": "uscita-star-wars-1977", "day": 25, "month": 5, "year": 1977,
        "kind": "event", "category": "culture", "subcategory": "cinema", "scope": "global",
        "countries": ["US"], "origin": "US",
        "title": {"it": "Esce «Guerre stellari» (Star Wars)", "en": "'Star Wars' premieres in cinemas", "es": "Se estrena «La guerra de las galaxias»"},
        "text": {"it": "Debutta nelle sale statunitensi il film di George Lucas «Guerre stellari», che diventa un fenomeno mondiale.",
                  "en": "George Lucas's 'Star Wars' opens in U.S. theaters and becomes a global phenomenon.",
                  "es": "La película «La guerra de las galaxias» de George Lucas se estrena en cines de EE. UU. y se convierte en un fenómeno mundial."},
        "wiki_url": "https://it.wikipedia.org/wiki/Guerre_stellari_(film)",
        "source": "Wikipedia 'Star Wars (film)' — uscita USA 25/5/1977.",
    },
    {
        "id": "benigni-oscar-vita-e-bella-1999", "day": 21, "month": 3, "year": 1999,
        "kind": "event", "category": "culture", "subcategory": "cinema", "scope": "global",
        "countries": ["IT"], "origin": "IT",
        "title": {"it": "Benigni vince l'Oscar con «La vita è bella»", "en": "Roberto Benigni wins an Oscar for 'Life Is Beautiful'", "es": "Benigni gana el Óscar con «La vida es bella»"},
        "text": {"it": "Alla 71ª cerimonia degli Oscar, Roberto Benigni vince come miglior attore per «La vita è bella», premiato anche come miglior film straniero.",
                  "en": "At the 71st Academy Awards, Roberto Benigni wins Best Actor for 'Life Is Beautiful', which also wins Best Foreign Language Film.",
                  "es": "En la 71.ª ceremonia de los Óscar, Roberto Benigni gana como mejor actor por «La vida es bella», que también gana como mejor película extranjera."},
        "wiki_url": "https://it.wikipedia.org/wiki/Premi_Oscar_1999",
        "source": "Wikipedia '71st Academy Awards' — 21/3/1999.",
    },
    {
        "id": "beatles-ed-sullivan-1964", "day": 9, "month": 2, "year": 1964,
        "kind": "event", "category": "culture", "subcategory": "music", "scope": "global",
        "countries": ["US", "GB"], "origin": "GB",
        "title": {"it": "I Beatles all'Ed Sullivan Show", "en": "The Beatles on The Ed Sullivan Show", "es": "Los Beatles en The Ed Sullivan Show"},
        "text": {"it": "I Beatles debuttano in TV negli USA all'Ed Sullivan Show davanti a circa 73 milioni di spettatori: inizia la «British Invasion».",
                  "en": "The Beatles make their U.S. TV debut on The Ed Sullivan Show before some 73 million viewers, launching the British Invasion.",
                  "es": "Los Beatles debutan en la televisión de EE. UU. en The Ed Sullivan Show ante unos 73 millones de espectadores, iniciando la «British Invasion»."},
        "wiki_url": "https://en.wikipedia.org/wiki/The_Ed_Sullivan_Show",
        "source": "Wikipedia 'The Ed Sullivan Show' — 9/2/1964.",
    },
    {
        "id": "nirvana-nevermind-1991", "day": 24, "month": 9, "year": 1991,
        "kind": "event", "category": "culture", "subcategory": "music", "scope": "global",
        "countries": ["US"], "origin": "US",
        "title": {"it": "Esce «Nevermind» dei Nirvana", "en": "Nirvana release 'Nevermind'", "es": "Nirvana publica «Nevermind»"},
        "text": {"it": "I Nirvana pubblicano l'album «Nevermind»: con «Smells Like Teen Spirit» il grunge conquista il mondo.",
                  "en": "Nirvana release the album 'Nevermind'; with 'Smells Like Teen Spirit', grunge conquers the world.",
                  "es": "Nirvana publica el álbum «Nevermind»; con «Smells Like Teen Spirit», el grunge conquista el mundo."},
        "wiki_url": "https://it.wikipedia.org/wiki/Nevermind",
        "source": "Wikipedia 'Nevermind' — 24/9/1991.",
    },
    {
        "id": "festival-woodstock-1969", "day": 15, "month": 8, "year": 1969,
        "kind": "event", "category": "culture", "subcategory": "music", "scope": "global",
        "countries": ["US"], "origin": "US",
        "title": {"it": "Inizia il festival di Woodstock", "en": "The Woodstock festival begins", "es": "Comienza el festival de Woodstock"},
        "text": {"it": "Nello Stato di New York si apre il festival di Woodstock, tre giorni di musica che diventano simbolo della cultura hippie.",
                  "en": "The Woodstock festival opens in New York State, three days of music that become a symbol of the hippie counterculture.",
                  "es": "En el estado de Nueva York comienza el festival de Woodstock, tres días de música que se vuelven símbolo de la cultura hippie."},
        "wiki_url": "https://it.wikipedia.org/wiki/Festival_di_Woodstock",
        "source": "Wikipedia 'Woodstock' — 15/8/1969.",
    },
    {
        "id": "prima-la-dolce-vita-1960", "day": 5, "month": 2, "year": 1960,
        "kind": "event", "category": "culture", "subcategory": "cinema", "scope": "global",
        "countries": ["IT"], "origin": "IT",
        "title": {"it": "Prima nazionale de «La dolce vita» di Fellini", "en": "National premiere of Fellini's 'La Dolce Vita'", "es": "Estreno nacional de «La dolce vita» de Fellini"},
        "text": {"it": "Al cinema Capitol di Milano debutta «La dolce vita» di Federico Fellini, capolavoro del cinema italiano poi premiato a Cannes.",
                  "en": "Federico Fellini's 'La Dolce Vita' has its national premiere at the Capitol cinema in Milan, an Italian masterpiece later awarded at Cannes.",
                  "es": "«La dolce vita» de Federico Fellini se estrena a nivel nacional en el cine Capitol de Milán, obra maestra del cine italiano premiada después en Cannes."},
        "wiki_url": "https://it.wikipedia.org/wiki/La_dolce_vita",
        "source": "Wikipedia IT 'La dolce vita' — prima nazionale 5/2/1960.",
    },
    # ===================== SCIENZA / TECNOLOGIA (con primati italiani) =====================
    {
        "id": "vislab-parma-shanghai-2010", "day": 20, "month": 7, "year": 2010,
        "kind": "event", "category": "science", "subcategory": "technology", "scope": "global",
        "countries": ["IT", "CN"], "origin": "IT",
        "title": {"it": "Da Parma a Shanghai: la sfida VisLab dell'auto senza pilota", "en": "VisLab's driverless challenge sets off from Parma to Shanghai", "es": "De Parma a Shanghái: el reto VisLab del coche sin conductor"},
        "text": {"it": "Il team di Alberto Broggi (VisLab, Università di Parma) avvia da Parma il primo viaggio intercontinentale di veicoli autonomi: 15.000 km fino a Shanghai.",
                  "en": "Alberto Broggi's team (VisLab, University of Parma) begins the first intercontinental driverless journey from Parma, covering 15,000 km to Shanghai.",
                  "es": "El equipo de Alberto Broggi (VisLab, Universidad de Parma) inicia en Parma el primer viaje intercontinental de vehículos autónomos: 15.000 km hasta Shanghái."},
        "wiki_url": "https://en.wikipedia.org/wiki/VisLab_Intercontinental_Autonomous_Challenge",
        "source": "Wikipedia + viac.vislab.it — partenza 20/7/2010.",
    },
    {
        "id": "marconi-primo-segnale-transatlantico-1901", "day": 12, "month": 12, "year": 1901,
        "kind": "event", "category": "science", "subcategory": "technology", "scope": "global",
        "countries": ["IT", "GB", "CA"], "origin": "IT",
        "title": {"it": "Marconi riceve il primo segnale radio attraverso l'Atlantico", "en": "Marconi receives the first radio signal across the Atlantic", "es": "Marconi recibe la primera señal de radio a través del Atlántico"},
        "text": {"it": "Guglielmo Marconi capta a Terranova la lettera 'S' in codice Morse inviata da Poldhu (Cornovaglia): la prima trasmissione radio transatlantica.",
                  "en": "Guglielmo Marconi picks up the Morse letter 'S' in Newfoundland, sent from Poldhu, Cornwall: the first transatlantic radio transmission.",
                  "es": "Guglielmo Marconi capta en Terranova la letra 'S' en Morse enviada desde Poldhu (Cornualles): la primera transmisión de radio transatlántica."},
        "wiki_url": "https://it.wikipedia.org/wiki/Guglielmo_Marconi",
        "source": "History.com / Wikipedia — 12/12/1901, Signal Hill.",
    },
    {
        "id": "volta-pila-elettrica-1800", "day": 20, "month": 3, "year": 1800,
        "kind": "event", "category": "science", "subcategory": "inventions", "scope": "global",
        "countries": ["IT", "GB"], "origin": "IT",
        "title": {"it": "Volta annuncia la pila: la prima batteria elettrica", "en": "Volta announces the pile: the first electric battery", "es": "Volta anuncia la pila: la primera batería eléctrica"},
        "text": {"it": "Alessandro Volta descrive la pila elettrica in una lettera alla Royal Society: la prima fonte stabile di corrente continua della storia.",
                  "en": "Alessandro Volta describes the voltaic pile in a letter to the Royal Society: the first steady source of continuous electric current.",
                  "es": "Alessandro Volta describe la pila eléctrica en una carta a la Royal Society: la primera fuente estable de corriente continua."},
        "wiki_url": "https://it.wikipedia.org/wiki/Alessandro_Volta",
        "source": "Britannica — lettera del 20/3/1800.",
    },
    {
        "id": "meucci-telefono-caveat-1871", "day": 28, "month": 12, "year": 1871,
        "kind": "event", "category": "science", "subcategory": "inventions", "scope": "global",
        "countries": ["IT", "US"], "origin": "IT",
        "title": {"it": "Meucci deposita il caveat del suo 'telegrafo parlante'", "en": "Meucci files the caveat for his 'talking telegraph'", "es": "Meucci presenta el caveat de su 'telégrafo parlante'"},
        "text": {"it": "Antonio Meucci deposita all'ufficio brevetti USA il caveat 'Sound Telegraph', documento chiave del suo lavoro pionieristico sul telefono.",
                  "en": "Antonio Meucci files the 'Sound Telegraph' caveat at the US Patent Office, a key record of his pioneering work on the telephone.",
                  "es": "Antonio Meucci presenta en la oficina de patentes de EE. UU. el caveat 'Sound Telegraph', pieza clave de su trabajo pionero sobre el teléfono."},
        "wiki_url": "https://it.wikipedia.org/wiki/Antonio_Meucci",
        "source": "Wikipedia / Congressional Record 2002 — caveat 28/12/1871.",
    },
    {
        "id": "fermi-prima-pila-atomica-1942", "day": 2, "month": 12, "year": 1942,
        "kind": "event", "category": "science", "subcategory": "physics", "scope": "global",
        "countries": ["IT", "US"], "origin": "IT",
        "title": {"it": "Fermi accende la prima reazione nucleare a catena controllata", "en": "Fermi triggers the first controlled nuclear chain reaction", "es": "Fermi logra la primera reacción nuclear en cadena controlada"},
        "text": {"it": "A Chicago, Enrico Fermi guida il reattore Chicago Pile-1 alla prima reazione nucleare a catena autosufficiente e controllata della storia.",
                  "en": "In Chicago, Enrico Fermi leads the Chicago Pile-1 reactor to the first self-sustaining, controlled nuclear chain reaction in history.",
                  "es": "En Chicago, Enrico Fermi dirige el reactor Chicago Pile-1 hacia la primera reacción nuclear en cadena autosostenida y controlada."},
        "wiki_url": "https://it.wikipedia.org/wiki/Chicago_Pile-1",
        "source": "Wikipedia 'Chicago Pile-1' — 2/12/1942.",
    },
    {
        "id": "levi-montalcini-nobel-1986", "day": 10, "month": 12, "year": 1986,
        "kind": "event", "category": "science", "subcategory": "medicine", "scope": "global",
        "countries": ["IT", "US"], "origin": "IT",
        "title": {"it": "Rita Levi-Montalcini riceve il Nobel per la Medicina", "en": "Rita Levi-Montalcini receives the Nobel Prize in Medicine", "es": "Rita Levi-Montalcini recibe el Nobel de Medicina"},
        "text": {"it": "Rita Levi-Montalcini riceve il Premio Nobel per la Medicina per la scoperta del fattore di crescita nervoso (NGF), condiviso con Stanley Cohen.",
                  "en": "Rita Levi-Montalcini receives the Nobel Prize in Medicine for discovering nerve growth factor (NGF), shared with Stanley Cohen.",
                  "es": "Rita Levi-Montalcini recibe el Nobel de Medicina por el descubrimiento del factor de crecimiento nervioso (NGF), compartido con Stanley Cohen."},
        "wiki_url": "https://www.nobelprize.org/prizes/medicine/1986/summary/",
        "source": "NobelPrize.org — Nobel Medicina 1986, cerimonia 10/12.",
    },
    {
        "id": "galileo-lune-di-giove-1610", "day": 7, "month": 1, "year": 1610,
        "kind": "event", "category": "science", "subcategory": "space", "scope": "global",
        "countries": ["IT"], "origin": "IT",
        "title": {"it": "Galileo scopre le prime lune di Giove", "en": "Galileo discovers the first moons of Jupiter", "es": "Galileo descubre las primeras lunas de Júpiter"},
        "text": {"it": "Con il suo cannocchiale Galileo Galilei osserva i satelliti di Giove: la prova che non tutto ruota attorno alla Terra.",
                  "en": "With his telescope Galileo Galilei observes Jupiter's satellites: proof that not everything orbits the Earth.",
                  "es": "Con su telescopio, Galileo Galilei observa los satélites de Júpiter: la prueba de que no todo gira alrededor de la Tierra."},
        "wiki_url": "https://it.wikipedia.org/wiki/Satelliti_medicei",
        "source": "Wikipedia 'Satelliti medicei' — 7/1/1610.",
    },
    {
        "id": "apollo-11-allunaggio-1969", "day": 20, "month": 7, "year": 1969,
        "kind": "event", "category": "science", "subcategory": "space", "scope": "global",
        "countries": ["US"], "origin": "US",
        "title": {"it": "Apollo 11: l'uomo cammina per la prima volta sulla Luna", "en": "Apollo 11: humans walk on the Moon for the first time", "es": "Apolo 11: el ser humano camina por primera vez en la Luna"},
        "text": {"it": "La missione Apollo 11 della NASA porta Neil Armstrong e Buzz Aldrin sulla superficie lunare: il primo allunaggio umano della storia.",
                  "en": "NASA's Apollo 11 mission lands Neil Armstrong and Buzz Aldrin on the lunar surface: the first crewed Moon landing in history.",
                  "es": "La misión Apolo 11 de la NASA lleva a Neil Armstrong y Buzz Aldrin a la superficie lunar: el primer alunizaje tripulado de la historia."},
        "wiki_url": "https://it.wikipedia.org/wiki/Apollo_11",
        "source": "Wikipedia / NASA — allunaggio 20/7/1969.",
    },
    {
        "id": "dna-doppia-elica-1953", "day": 25, "month": 4, "year": 1953,
        "kind": "event", "category": "science", "subcategory": "biology", "scope": "global",
        "countries": ["GB", "US"], "origin": "GB",
        "title": {"it": "Watson e Crick pubblicano la doppia elica del DNA", "en": "Watson and Crick publish the DNA double-helix structure", "es": "Watson y Crick publican la estructura en doble hélice del ADN"},
        "text": {"it": "Su Nature, James Watson e Francis Crick descrivono la doppia elica del DNA, svelando come si conserva e si copia l'informazione genetica.",
                  "en": "In Nature, James Watson and Francis Crick describe the DNA double helix, revealing how genetic information is stored and copied.",
                  "es": "En Nature, James Watson y Francis Crick describen la doble hélice del ADN, revelando cómo se guarda y copia la información genética."},
        "wiki_url": "https://en.wikipedia.org/wiki/Molecular_Structure_of_Nucleic_Acids:_A_Structure_for_Deoxyribose_Nucleic_Acid",
        "source": "Nature / genome.gov — 25/4/1953.",
    },
    {
        "id": "prima-immagine-buco-nero-2019", "day": 10, "month": 4, "year": 2019,
        "kind": "event", "category": "science", "subcategory": "space", "scope": "global",
        "countries": ["US", "DE", "CL"], "origin": "US",
        "title": {"it": "Svelata la prima immagine di un buco nero", "en": "The first image of a black hole is revealed", "es": "Se revela la primera imagen de un agujero negro"},
        "text": {"it": "La collaborazione Event Horizon Telescope presenta la prima immagine diretta di un buco nero, quello al centro della galassia M87.",
                  "en": "The Event Horizon Telescope collaboration presents the first direct image of a black hole, at the centre of galaxy M87.",
                  "es": "La colaboración Event Horizon Telescope presenta la primera imagen directa de un agujero negro, en el centro de la galaxia M87."},
        "wiki_url": "https://en.wikipedia.org/wiki/Messier_87",
        "source": "EHT / NSF / ESO — annuncio 10/4/2019.",
    },
    {
        "id": "fleming-scoperta-penicillina-1928", "day": 28, "month": 9, "year": 1928,
        "kind": "event", "category": "science", "subcategory": "medicine", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Fleming scopre la penicillina, il primo antibiotico", "en": "Fleming discovers penicillin, the first antibiotic", "es": "Fleming descubre la penicilina, el primer antibiótico"},
        "text": {"it": "Alexander Fleming nota che una muffa (Penicillium) uccide i batteri in una piastra: la scoperta della penicillina, primo antibiotico.",
                  "en": "Alexander Fleming notices that a mould (Penicillium) kills bacteria in a dish: the discovery of penicillin, the first antibiotic.",
                  "es": "Alexander Fleming observa que un moho (Penicillium) mata bacterias en una placa: el descubrimiento de la penicilina, el primer antibiótico."},
        "wiki_url": "https://it.wikipedia.org/wiki/Penicillina",
        "source": "Live Science / CBS — 28/9/1928.",
    },
    {
        "id": "wright-primo-volo-1903", "day": 17, "month": 12, "year": 1903,
        "kind": "event", "category": "science", "subcategory": "aviation", "scope": "global",
        "countries": ["US"], "origin": "US",
        "title": {"it": "I fratelli Wright compiono il primo volo a motore", "en": "The Wright brothers make the first powered flight", "es": "Los hermanos Wright realizan el primer vuelo a motor"},
        "text": {"it": "A Kitty Hawk, Orville e Wilbur Wright effettuano il primo volo controllato di un velivolo a motore più pesante dell'aria.",
                  "en": "At Kitty Hawk, Orville and Wilbur Wright achieve the first controlled flight of a powered, heavier-than-air aircraft.",
                  "es": "En Kitty Hawk, Orville y Wilbur Wright logran el primer vuelo controlado de un avión a motor más pesado que el aire."},
        "wiki_url": "https://it.wikipedia.org/wiki/Fratelli_Wright",
        "source": "Wikipedia 'Fratelli Wright' — 17/12/1903.",
    },
    {
        "id": "primo-trapianto-cuore-1967", "day": 3, "month": 12, "year": 1967,
        "kind": "event", "category": "science", "subcategory": "medicine", "scope": "global",
        "countries": ["ZA"], "origin": "ZA",
        "title": {"it": "Barnard esegue il primo trapianto di cuore umano", "en": "Barnard performs the first human heart transplant", "es": "Barnard realiza el primer trasplante de corazón humano"},
        "text": {"it": "A Città del Capo, Christiaan Barnard esegue il primo trapianto di cuore da uomo a uomo, sul paziente Louis Washkansky.",
                  "en": "In Cape Town, Christiaan Barnard performs the first human-to-human heart transplant, on patient Louis Washkansky.",
                  "es": "En Ciudad del Cabo, Christiaan Barnard realiza el primer trasplante de corazón de humano a humano, en el paciente Louis Washkansky."},
        "wiki_url": "https://en.wikipedia.org/wiki/Christiaan_Barnard",
        "source": "History.com / Britannica — 3/12/1967.",
    },
    {
        "id": "primo-sito-web-1991", "day": 6, "month": 8, "year": 1991,
        "kind": "event", "category": "science", "subcategory": "technology", "scope": "global",
        "countries": ["CH", "GB"], "origin": "GB",
        "title": {"it": "Nasce il primo sito web della storia", "en": "The first website in history goes online", "es": "Nace el primer sitio web de la historia"},
        "text": {"it": "Al CERN, Tim Berners-Lee pubblica il primo sito web e annuncia pubblicamente il World Wide Web, dando il via al web moderno.",
                  "en": "At CERN, Tim Berners-Lee publishes the first website and publicly announces the World Wide Web, launching the modern web.",
                  "es": "En el CERN, Tim Berners-Lee publica el primer sitio web y anuncia públicamente la World Wide Web, dando inicio a la web moderna."},
        "wiki_url": "https://en.wikipedia.org/wiki/World_Wide_Web",
        "source": "CERN / Popular Science — 6/8/1991.",
    },
    # ===================== ORGOGLIO BRITANNICO =====================
    {
        "id": "newton-principia-1687", "day": 5, "month": 7, "year": 1687,
        "kind": "event", "category": "science", "subcategory": "physics", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Newton pubblica i Principia", "en": "Newton publishes the Principia", "es": "Newton publica los Principia"},
        "text": {"it": "Isaac Newton pubblica i 'Philosophiae Naturalis Principia Mathematica', che espongono le leggi del moto e la gravitazione universale.",
                  "en": "Isaac Newton publishes 'Philosophiae Naturalis Principia Mathematica', setting out the laws of motion and universal gravitation.",
                  "es": "Isaac Newton publica los 'Philosophiae Naturalis Principia Mathematica', que exponen las leyes del movimiento y la gravitación universal."},
        "wiki_url": "https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica",
        "source": "Wikipedia / Astronomy.com — 5/7/1687.",
    },
    {
        "id": "darwin-origin-species-1859", "day": 24, "month": 11, "year": 1859,
        "kind": "event", "category": "science", "subcategory": "biology", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Darwin pubblica «L'origine delle specie»", "en": "Darwin publishes 'On the Origin of Species'", "es": "Darwin publica «El origen de las especies»"},
        "text": {"it": "Charles Darwin pubblica «L'origine delle specie», introducendo la teoria dell'evoluzione tramite la selezione naturale.",
                  "en": "Charles Darwin publishes 'On the Origin of Species', introducing the theory of evolution by natural selection.",
                  "es": "Charles Darwin publica «El origen de las especies», introduciendo la teoría de la evolución por selección natural."},
        "wiki_url": "https://en.wikipedia.org/wiki/On_the_Origin_of_Species",
        "source": "Wikipedia / History.com — prima edizione 24/11/1859.",
    },
    {
        "id": "turing-born-1912", "day": 23, "month": 6, "year": 1912,
        "kind": "event", "category": "science", "subcategory": "technology", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Nasce Alan Turing", "en": "Alan Turing is born", "es": "Nace Alan Turing"},
        "text": {"it": "Nasce a Londra Alan Turing, padre dell'informatica teorica e decrittatore di Enigma a Bletchley Park.",
                  "en": "Alan Turing, father of theoretical computer science and Enigma codebreaker at Bletchley Park, is born in London.",
                  "es": "Nace en Londres Alan Turing, padre de la informática teórica y descifrador de Enigma en Bletchley Park."},
        "wiki_url": "https://en.wikipedia.org/wiki/Alan_Turing",
        "source": "Wikipedia / Britannica — nato 23/6/1912.",
    },
    {
        "id": "harry-potter-philosophers-stone-1997", "day": 26, "month": 6, "year": 1997,
        "kind": "event", "category": "culture", "subcategory": "literature", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Esce il primo libro di Harry Potter", "en": "The first Harry Potter book is published", "es": "Se publica el primer libro de Harry Potter"},
        "text": {"it": "Bloomsbury pubblica «Harry Potter e la Pietra Filosofale», primo romanzo di J.K. Rowling della saga più venduta al mondo.",
                  "en": "Bloomsbury publishes 'Harry Potter and the Philosopher's Stone', J.K. Rowling's first novel in the best-selling saga.",
                  "es": "Bloomsbury publica «Harry Potter y la piedra filosofal», primera novela de J.K. Rowling de la saga más vendida del mundo."},
        "wiki_url": "https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone",
        "source": "Wikipedia / Britannica — pubblicato nel Regno Unito 26/6/1997.",
    },
    {
        "id": "beatles-love-me-do-1962", "day": 5, "month": 10, "year": 1962,
        "kind": "event", "category": "culture", "subcategory": "music", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "I Beatles pubblicano 'Love Me Do'", "en": "The Beatles release 'Love Me Do'", "es": "Los Beatles publican 'Love Me Do'"},
        "text": {"it": "I Beatles pubblicano nel Regno Unito il loro primo singolo, 'Love Me Do', segnando l'inizio della loro carriera discografica.",
                  "en": "The Beatles release their first single, 'Love Me Do', in the UK, marking the start of their recording career.",
                  "es": "Los Beatles publican en el Reino Unido su primer sencillo, 'Love Me Do', marcando el inicio de su carrera discográfica."},
        "wiki_url": "https://en.wikipedia.org/wiki/Love_Me_Do",
        "source": "Wikipedia / The Beatles Bible — 5/10/1962.",
    },
    {
        "id": "queen-bohemian-rhapsody-1975", "day": 31, "month": 10, "year": 1975,
        "kind": "event", "category": "culture", "subcategory": "music", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Esce 'Bohemian Rhapsody' dei Queen", "en": "Queen release 'Bohemian Rhapsody'", "es": "Queen publica 'Bohemian Rhapsody'"},
        "text": {"it": "I Queen pubblicano il singolo 'Bohemian Rhapsody', scritto da Freddie Mercury, che resterà in vetta alla classifica britannica per nove settimane.",
                  "en": "Queen release the single 'Bohemian Rhapsody', written by Freddie Mercury, which topped the UK chart for nine weeks.",
                  "es": "Queen publica el sencillo 'Bohemian Rhapsody', escrito por Freddie Mercury, que encabezó la lista británica durante nueve semanas."},
        "wiki_url": "https://en.wikipedia.org/wiki/Bohemian_Rhapsody",
        "source": "Wikipedia / Billboard — 31/10/1975.",
    },
    {
        "id": "live-aid-wembley-1985", "day": 13, "month": 7, "year": 1985,
        "kind": "event", "category": "culture", "subcategory": "music", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Live Aid a Wembley", "en": "Live Aid at Wembley", "es": "Live Aid en Wembley"},
        "text": {"it": "Il concerto benefico Live Aid, ideato da Bob Geldof e Midge Ure, si tiene allo stadio di Wembley per la lotta alla carestia in Etiopia.",
                  "en": "The Live Aid benefit concert, conceived by Bob Geldof and Midge Ure, is held at Wembley Stadium to fight the Ethiopian famine.",
                  "es": "El concierto benéfico Live Aid, ideado por Bob Geldof y Midge Ure, se celebra en el estadio de Wembley contra la hambruna en Etiopía."},
        "wiki_url": "https://en.wikipedia.org/wiki/Live_Aid",
        "source": "Wikipedia / Britannica — 13/7/1985.",
    },
    {
        "id": "elizabeth-ii-coronation-1953", "day": 2, "month": 6, "year": 1953,
        "kind": "event", "category": "politics", "subcategory": "monarchies", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Incoronazione di Elisabetta II", "en": "Coronation of Elizabeth II", "es": "Coronación de Isabel II"},
        "text": {"it": "Elisabetta II viene incoronata nell'Abbazia di Westminster: è la prima incoronazione trasmessa in televisione.",
                  "en": "Elizabeth II is crowned at Westminster Abbey; it is the first coronation to be televised.",
                  "es": "Isabel II es coronada en la Abadía de Westminster; es la primera coronación televisada."},
        "wiki_url": "https://en.wikipedia.org/wiki/Coronation_of_Elizabeth_II",
        "source": "Wikipedia / Royal.uk — 2/6/1953.",
    },
    {
        "id": "elizabeth-ii-death-2022", "day": 8, "month": 9, "year": 2022,
        "kind": "event", "category": "politics", "subcategory": "monarchies", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Morte della regina Elisabetta II", "en": "Death of Queen Elizabeth II", "es": "Muerte de la reina Isabel II"},
        "text": {"it": "La regina Elisabetta II muore a 96 anni nel castello di Balmoral, dopo 70 anni di regno, il più lungo della storia britannica.",
                  "en": "Queen Elizabeth II dies aged 96 at Balmoral Castle after a 70-year reign, the longest in British history.",
                  "es": "La reina Isabel II muere a los 96 años en el castillo de Balmoral tras 70 años de reinado, el más largo de la historia británica."},
        "wiki_url": "https://en.wikipedia.org/wiki/Death_of_Elizabeth_II",
        "source": "Washington Post / NPR — 8/9/2022.",
    },
    {
        "id": "nhs-founded-1948", "day": 5, "month": 7, "year": 1948,
        "kind": "event", "category": "politics", "subcategory": "human_rights", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Nasce il Servizio Sanitario Nazionale (NHS)", "en": "The National Health Service (NHS) is founded", "es": "Se funda el Servicio Nacional de Salud (NHS)"},
        "text": {"it": "Nel Regno Unito apre l'NHS, primo sistema sanitario universale gratuito nel momento dell'uso, voluto da Aneurin Bevan.",
                  "en": "The UK launches the NHS, the first universal health service free at the point of use, championed by Aneurin Bevan.",
                  "es": "En el Reino Unido abre el NHS, primer sistema sanitario universal gratuito en el momento de uso, impulsado por Aneurin Bevan."},
        "wiki_url": "https://en.wikipedia.org/wiki/National_Health_Service_(England)",
        "source": "National Archives / gov.uk — 5/7/1948.",
    },
    {
        "id": "churchill-fight-on-beaches-1940", "day": 4, "month": 6, "year": 1940,
        "kind": "event", "category": "wars", "subcategory": "world_wars", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Churchill: 'We shall fight on the beaches'", "en": "Churchill's 'We shall fight on the beaches' speech", "es": "Discurso de Churchill: 'We shall fight on the beaches'"},
        "text": {"it": "Dopo l'evacuazione di Dunkerque, Winston Churchill pronuncia alla Camera dei Comuni il celebre discorso 'We shall fight on the beaches'.",
                  "en": "After the Dunkirk evacuation, Winston Churchill delivers his famous 'We shall fight on the beaches' speech to the House of Commons.",
                  "es": "Tras la evacuación de Dunkerque, Winston Churchill pronuncia en la Cámara de los Comunes su famoso discurso 'We shall fight on the beaches'."},
        "wiki_url": "https://en.wikipedia.org/wiki/We_shall_fight_on_the_beaches",
        "source": "Wikipedia / International Churchill Society — 4/6/1940.",
    },
    {
        "id": "bannister-four-minute-mile-1954", "day": 6, "month": 5, "year": 1954,
        "kind": "event", "category": "sports", "subcategory": "athletics", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Bannister corre il primo miglio sotto i 4 minuti", "en": "Bannister runs the first sub-four-minute mile", "es": "Bannister corre la primera milla en menos de 4 minutos"},
        "text": {"it": "A Oxford, Roger Bannister diventa il primo uomo a correre il miglio in meno di quattro minuti, con 3:59,4.",
                  "en": "At Oxford, Roger Bannister becomes the first man to run a mile in under four minutes, in 3:59.4.",
                  "es": "En Oxford, Roger Bannister se convierte en el primer hombre en correr la milla en menos de cuatro minutos, con 3:59,4."},
        "wiki_url": "https://en.wikipedia.org/wiki/Four-minute_mile",
        "source": "History.com / World Athletics — 6/5/1954.",
    },
    {
        "id": "first-wimbledon-championship-1877", "day": 9, "month": 7, "year": 1877,
        "kind": "event", "category": "sports", "subcategory": "tennis", "scope": "global",
        "countries": ["GB"], "origin": "GB",
        "title": {"it": "Primo torneo di Wimbledon", "en": "First Wimbledon Championships", "es": "Primer torneo de Wimbledon"},
        "text": {"it": "Iniziano a Londra i primi Campionati di Wimbledon, il torneo di tennis più antico al mondo, con il solo singolare maschile.",
                  "en": "The first Wimbledon Championships, the oldest tennis tournament in the world, begin in London with a men's singles event only.",
                  "es": "Comienzan en Londres los primeros Campeonatos de Wimbledon, el torneo de tenis más antiguo del mundo, solo con individual masculino."},
        "wiki_url": "https://en.wikipedia.org/wiki/1877_Wimbledon_Championship",
        "source": "Wikipedia / History.com — 9/7/1877.",
    },
    # ===================== ORGOGLIO SPAGNOLO / ISPANICO =====================
    {
        "id": "picasso-nacimiento-1881", "day": 25, "month": 10, "year": 1881,
        "kind": "birth", "category": "culture", "subcategory": "art", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Nasce Pablo Picasso", "en": "Pablo Picasso is born", "es": "Nace Pablo Picasso"},
        "text": {"it": "A Málaga nasce Pablo Picasso, tra i pittori più influenti del Novecento e cofondatore del cubismo.",
                  "en": "Pablo Picasso, one of the most influential painters of the 20th century and co-founder of Cubism, is born in Málaga.",
                  "es": "En Málaga nace Pablo Picasso, uno de los pintores más influyentes del siglo XX y cofundador del cubismo."},
        "wiki_url": "https://es.wikipedia.org/wiki/Pablo_Picasso",
        "source": "Museo Casa Natal Picasso / Wikipedia — 25/10/1881.",
    },
    {
        "id": "bombardeo-guernica-1937", "day": 26, "month": 4, "year": 1937,
        "kind": "event", "category": "wars", "subcategory": "civil_wars", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Bombardamento di Guernica", "en": "Bombing of Guernica", "es": "Bombardeo de Guernica"},
        "text": {"it": "Durante la guerra civile l'aviazione tedesca e italiana rade al suolo Guernica; l'orrore ispirerà il celebre dipinto di Picasso.",
                  "en": "During the Civil War, German and Italian aircraft devastate Guernica; the horror would inspire Picasso's famous painting.",
                  "es": "Durante la Guerra Civil, la aviación alemana e italiana arrasa Guernica; el horror inspiraría el célebre cuadro de Picasso."},
        "wiki_url": "https://es.wikipedia.org/wiki/Bombardeo_de_Guernica",
        "source": "Wikipedia ES / Patrimonio Cultural de Defensa — 26/4/1937.",
    },
    {
        "id": "cervantes-muerte-1616", "day": 22, "month": 4, "year": 1616,
        "kind": "death", "category": "culture", "subcategory": "literature", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Muore Miguel de Cervantes", "en": "Miguel de Cervantes dies", "es": "Muere Miguel de Cervantes"},
        "text": {"it": "Muore a Madrid Miguel de Cervantes, autore del 'Don Chisciotte', considerato il primo romanzo moderno.",
                  "en": "Miguel de Cervantes, author of 'Don Quixote', regarded as the first modern novel, dies in Madrid.",
                  "es": "Muere en Madrid Miguel de Cervantes, autor de 'Don Quijote', considerada la primera novela moderna."},
        "wiki_url": "https://es.wikipedia.org/wiki/Miguel_de_Cervantes",
        "source": "Real Academia Española / Wikipedia — morte 22/4/1616.",
    },
    {
        "id": "sagrada-familia-primera-piedra-1882", "day": 19, "month": 3, "year": 1882,
        "kind": "event", "category": "culture", "subcategory": "art", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Prima pietra della Sagrada Família", "en": "First stone of the Sagrada Família", "es": "Primera piedra de la Sagrada Família"},
        "text": {"it": "A Barcellona viene posata la prima pietra della Sagrada Família; l'anno dopo Gaudí ne assumerà la direzione.",
                  "en": "The first stone of the Sagrada Família is laid in Barcelona; Gaudí would take over the project a year later.",
                  "es": "En Barcelona se coloca la primera piedra de la Sagrada Família; Gaudí asumiría el proyecto un año después."},
        "wiki_url": "https://es.wikipedia.org/wiki/Templo_Expiatorio_de_la_Sagrada_Familia",
        "source": "Basílica de la Sagrada Família / Wikipedia — 19/3/1882.",
    },
    {
        "id": "gaudi-muerte-1926", "day": 10, "month": 6, "year": 1926,
        "kind": "death", "category": "culture", "subcategory": "art", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Muore Antoni Gaudí", "en": "Antoni Gaudí dies", "es": "Muere Antoni Gaudí"},
        "text": {"it": "Muore a Barcellona l'architetto modernista Antoni Gaudí, tre giorni dopo essere stato investito da un tram.",
                  "en": "Modernist architect Antoni Gaudí dies in Barcelona, three days after being struck by a tram.",
                  "es": "Muere en Barcelona el arquitecto modernista Antoni Gaudí, tres días después de ser atropellado por un tranvía."},
        "wiki_url": "https://es.wikipedia.org/wiki/Antoni_Gaud%C3%AD",
        "source": "Wikipedia / Casa Batlló — morte 10/6/1926.",
    },
    {
        "id": "constitucion-espanola-referendum-1978", "day": 6, "month": 12, "year": 1978,
        "kind": "event", "category": "politics", "subcategory": "elections", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Referendum sulla Costituzione spagnola", "en": "Spanish Constitution referendum", "es": "Referéndum de la Constitución española"},
        "text": {"it": "Gli spagnoli approvano in referendum la Costituzione del 1978, pilastro della transizione democratica.",
                  "en": "Spaniards approve the 1978 Constitution by referendum, a cornerstone of the democratic transition.",
                  "es": "Los españoles aprueban en referéndum la Constitución de 1978, pilar de la transición democrática."},
        "wiki_url": "https://es.wikipedia.org/wiki/Constituci%C3%B3n_espa%C3%B1ola_de_1978",
        "source": "Congreso / Senado / Wikipedia — referendum 6/12/1978.",
    },
    {
        "id": "muerte-franco-1975", "day": 20, "month": 11, "year": 1975,
        "kind": "death", "category": "politics", "subcategory": "human_rights", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Morte di Francisco Franco", "en": "Death of Francisco Franco", "es": "Muerte de Francisco Franco"},
        "text": {"it": "Muore a Madrid il dittatore Francisco Franco, aprendo la strada al ritorno della democrazia in Spagna.",
                  "en": "Dictator Francisco Franco dies in Madrid, opening the way to the return of democracy in Spain.",
                  "es": "Muere en Madrid el dictador Francisco Franco, abriendo el camino al regreso de la democracia en España."},
        "wiki_url": "https://es.wikipedia.org/wiki/Francisco_Franco",
        "source": "Wikipedia — morte 20/11/1975.",
    },
    {
        "id": "ramon-y-cajal-nobel-1906", "day": 10, "month": 12, "year": 1906,
        "kind": "event", "category": "science", "subcategory": "medicine", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Nobel per la Medicina a Ramón y Cajal", "en": "Nobel Prize in Medicine for Ramón y Cajal", "es": "Nobel de Medicina para Ramón y Cajal"},
        "text": {"it": "Santiago Ramón y Cajal riceve il Nobel per la Medicina per gli studi sulla struttura del sistema nervoso.",
                  "en": "Santiago Ramón y Cajal receives the Nobel Prize in Medicine for his work on the structure of the nervous system.",
                  "es": "Santiago Ramón y Cajal recibe el Nobel de Medicina por sus estudios sobre la estructura del sistema nervioso."},
        "wiki_url": "https://es.wikipedia.org/wiki/Santiago_Ram%C3%B3n_y_Cajal",
        "source": "NobelPrize.org — cerimonia 10/12/1906.",
    },
    {
        "id": "severo-ochoa-nobel-1959", "day": 10, "month": 12, "year": 1959,
        "kind": "event", "category": "science", "subcategory": "medicine", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Nobel per la Medicina a Severo Ochoa", "en": "Nobel Prize in Medicine for Severo Ochoa", "es": "Nobel de Medicina para Severo Ochoa"},
        "text": {"it": "Severo Ochoa riceve il Nobel per la Medicina per la scoperta dei meccanismi di sintesi dell'RNA.",
                  "en": "Severo Ochoa receives the Nobel Prize in Medicine for discovering the mechanisms of RNA synthesis.",
                  "es": "Severo Ochoa recibe el Nobel de Medicina por descubrir los mecanismos de síntesis del ARN."},
        "wiki_url": "https://es.wikipedia.org/wiki/Severo_Ochoa",
        "source": "NobelPrize.org — cerimonia 10/12/1959.",
    },
    {
        "id": "dali-nacimiento-1904", "day": 11, "month": 5, "year": 1904,
        "kind": "birth", "category": "culture", "subcategory": "art", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Nasce Salvador Dalí", "en": "Salvador Dalí is born", "es": "Nace Salvador Dalí"},
        "text": {"it": "A Figueres nasce Salvador Dalí, tra i massimi esponenti del surrealismo.",
                  "en": "Salvador Dalí, one of the leading figures of Surrealism, is born in Figueres.",
                  "es": "En Figueres nace Salvador Dalí, uno de los máximos exponentes del surrealismo."},
        "wiki_url": "https://es.wikipedia.org/wiki/Salvador_Dal%C3%AD",
        "source": "Wikipedia — nascita 11/5/1904.",
    },
    {
        "id": "almodovar-oscar-2000", "day": 26, "month": 3, "year": 2000,
        "kind": "event", "category": "culture", "subcategory": "cinema", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Oscar per Almodóvar con 'Tutto su mia madre'", "en": "Oscar for Almodóvar with 'All About My Mother'", "es": "Óscar para Almodóvar con 'Todo sobre mi madre'"},
        "text": {"it": "'Tutto su mia madre' di Pedro Almodóvar vince l'Oscar per il miglior film in lingua straniera.",
                  "en": "Pedro Almodóvar's 'All About My Mother' wins the Oscar for Best Foreign Language Film.",
                  "es": "'Todo sobre mi madre', de Pedro Almodóvar, gana el Óscar a la mejor película de habla no inglesa."},
        "wiki_url": "https://es.wikipedia.org/wiki/Todo_sobre_mi_madre",
        "source": "72ª cerimonia degli Oscar — 26/3/2000.",
    },
    {
        "id": "nadal-primer-roland-garros-2005", "day": 5, "month": 6, "year": 2005,
        "kind": "event", "category": "sports", "subcategory": "tennis", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Primo Roland Garros di Rafael Nadal", "en": "Rafael Nadal's first Roland Garros", "es": "Primer Roland Garros de Rafael Nadal"},
        "text": {"it": "A 19 anni Rafael Nadal vince il suo primo Roland Garros battendo in finale Mariano Puerta.",
                  "en": "At 19, Rafael Nadal wins his first Roland Garros, beating Mariano Puerta in the final.",
                  "es": "Con 19 años, Rafael Nadal gana su primer Roland Garros al vencer a Mariano Puerta en la final."},
        "wiki_url": "https://es.wikipedia.org/wiki/Torneo_de_Roland_Garros_2005",
        "source": "ATP Tour / Wikipedia — finale 5/6/2005.",
    },
    {
        "id": "barcelona-juegos-olimpicos-1992", "day": 25, "month": 7, "year": 1992,
        "kind": "event", "category": "sports", "subcategory": "olympics", "scope": "global",
        "countries": ["ES"], "origin": "ES",
        "title": {"it": "Cerimonia d'apertura di Barcellona 1992", "en": "Opening ceremony of Barcelona 1992", "es": "Ceremonia de apertura de Barcelona 1992"},
        "text": {"it": "A Barcellona si aprono i Giochi Olimpici del 1992, seguiti da miliardi di spettatori in tutto il mondo.",
                  "en": "The 1992 Olympic Games open in Barcelona, watched by billions of viewers around the world.",
                  "es": "En Barcelona se inauguran los Juegos Olímpicos de 1992, seguidos por miles de millones de espectadores."},
        "wiki_url": "https://es.wikipedia.org/wiki/Juegos_Ol%C3%ADmpicos_de_Barcelona_1992",
        "source": "Wikipedia — apertura 25/7/1992.",
    },
]


def _entry(c: dict, current_year: int) -> dict:
    """Espande una voce compatta nella forma completa attesa dal backend."""
    title = c.get("title", {})
    text = c.get("text", {})
    wiki = c.get("wiki_url") or {}
    if isinstance(wiki, str):
        wiki = {l: wiki for l in LANGS}
    text_by_lang = {l: text.get(l, "") for l in LANGS}
    return {
        "id": f"curated-{c['id']}",
        "kind": c.get("kind", "event"),
        "year": c["year"],
        "years_ago": current_year - c["year"],
        "text_by_lang": text_by_lang,
        "title_by_lang": {l: title.get(l, "") for l in LANGS},
        "extract_by_lang": dict(text_by_lang),
        "image_url": c.get("image_url") or IMAGE_URLS.get(c["id"]),
        "wiki_urls": {l: wiki.get(l, "") for l in LANGS},
        "category": c.get("category", "sports"),
        "subcategory": c.get("subcategory"),
        "scope": c.get("scope", "global"),
        "sources": list(LANGS),
        "native_langs": list(LANGS),
        "countries": c.get("countries", []),
        "origin": c.get("origin"),
        "fame": 999,  # curati = sempre rilevanti, mai scartati dalla curation
        "month": c["month"],
        "day": c["day"],
        "curated": True,
    }


def curated_for_day(month: int, day: int, current_year: int) -> List[dict]:
    """Eventi curati per un dato giorno del calendario, pronti per il feed."""
    return [
        _entry(c, current_year)
        for c in CURATED_EVENTS
        if c.get("month") == month and c.get("day") == day
    ]
